version: 2
run:
  timeout: 3m
  tests: true

linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - ineffassign
    - unused
    - errcheck
    - misspell

linters-settings:
  misspell:
    locale: US

issues:
  exclude-use-default: false
