version: "2"

run:
  timeout: 3m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - ineffassign
    - unused
    - errcheck
    - misspell

# Simplified for v2 schema: removed deprecated disable-all, issues.exclude-use-default, and linters-settings
